CREATE WAREHOUSE IF NOT EXISTS ecom_wh
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS ecom_db;
CREATE SCHEMA IF NOT EXISTS ecom_db.ecom_schema;

USE WAREHOUSE ecom_wh;
USE DATABASE ecom_db;
USE SCHEMA ecom_schema;
